CREATE TABLE categories (id INT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id));
CREATE TABLE todolists (id INT NOT NULL, category_id INT NOT NULL, name VARCHAR(255) NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status BOOLEAN DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_AD289A112469DE2 ON todolists (category_id);
CREATE SEQUENCE categories_id_seq INCREMENT BY 1 MINVALUE 100 START 100;
CREATE SEQUENCE todolists_id_seq INCREMENT BY 1 MINVALUE 100 START 100;
ALTER TABLE todolists ADD CONSTRAINT FK_AD289A112469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
